apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: http-echo-service
  namespace: ace-demo-op
  labels: {}
spec:
  adminServerSecure: false
  barURL: >-
    https://github.com/venmaniselvan/ace-operator-bar/raw/main/TestHttpApp.bar
  configurations:
    - github-barauth
  createDashboardUsers: true
  designerFlowsOperationMode: disabled
  enableMetrics: true
  license:
    accept: true
    license: L-LFMR-BTD75V
    use: CloudPakForIntegrationNonProductionFREE
  pod:
    containers:
      runtime:
        resources:
          limits:
            cpu: 300m
            memory: 350Mi
          requests:
            cpu: 300m
            memory: 300Mi
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  version: '12.0.9.0-r2'
